### ISSUE TITLE
Metric

### ISSUE THREAD

**Issue by Mia961205** [idejie/OAN#1]
Hello, it seems that there is only the training phase when running the main.py file, and there is no verification and test phase. There is no value of evaluation index in the output result. Could you please provide the relevant code for evaluation？Thanks a lot.

**Comment by idejie** [comment]
Recently, there are many things to be busy, so there is no time to update the code. It is recommended to contact the author of the original paper. I will update this code once I have time.

**Comment by Mia961205** [comment]
Thank you for your reply. By the way, how long did it take you to run the code epoch = 24 for this project?

**Comment by idejie** [comment]
So sorry for my late response.

Because failed to contact the authors of this paper,  I decided to stop updating this repo.

If you have an interest in cross-modal retrieval, you can move your attention to our recent work in ICMR2020.

Paper: "Deep Semantic-Alignment Hashing for Unsupervised Cross-Modal Retrieval"
Code: https://github.com/idejie/DSAH
